# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
  InjectAlmOctaneTasks: 'true'
  AlmOctaneConnection11: 'almoctane'
  AlmOctaneConnection11Workspaces: '1003'
  AlmOctaneLogLevel: 'debug'

jobs:
- job: AlmOctanePipelineStart
  condition: always()
  
- job: A
  dependsOn: AlmOctanePipelineStart
  steps:
  - bash: echo "A"

- job: C
  dependsOn: AlmOctanePipelineStart
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: echo "A"
  
- job: AlmOctanePipelineEnd
  condition: always()
  dependsOn:
  - AlmOctanePipelineStart
  - A
  - C